apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf
  namespace: open5gs
  labels:
    app: lab-open5gs-amf
spec:
  selector:
    app: lab-open5gs-amf
  ports:
    - name: http
      port: 80
      targetPort: 80
