apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open5gs-amf
  namespace: open5gs
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: lab-open5gs-amf
  namespaceSelector:
    matchNames:
      - open5gs
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
